# Generated by Django 4.0.5 on 2022-06-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_contact_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(default=254, max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='caption_a',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='caption_b',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
