# Generated by Django 4.0.5 on 2022-06-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_description_project_long_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
