# Generated by Django 4.0.5 on 2022-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_rename_creator_project_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='username',
        ),
    ]
