# Generated by Django 4.0.5 on 2022-06-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_rename_display_name_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(default=254),
        ),
    ]
