# Generated by Django 4.0.5 on 2022-06-13 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0011_rename_creator_profile_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(null=True, to='review.project'),
        ),
    ]
